name: store
description: Store.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^4.5.0
  flutter_mobx: ^2.0.2
  dartz: ^0.10.1
  dio: ^4.0.4
  mocktail: ^0.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  mobx_codegen: 
  build_runner: ^2.1.7
flutter:
  uses-material-design: true
